### PR TITLE
Alter when the list of script tags is returned to make sure we can handle libraries with more than one JS file

### LINKED ISSUE #5: Only the first JS file in a library's `js` collection seems to be output to the page
E.g., with this library:

```yaml
global:
  css:
    theme:
      dist/style.css: {}
      dist/tailwind.css: {}
  js:
    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
```
The only output is:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>`

I think maybe because $output gets wiped out by each iteration of the forEach loop, then only passed to $stringLoader->render once.

### PR DESCRIPTION
**Pull request by philwolstenholme**
This seems to fix #5 for me

### CODE REVIEW

**Review by evanmwillhite — APPROVED** [review]
Works great! Thank you again!!

**Comment by agarzola** [comment]
Any chance we could get a new release tag with this fix?

**Comment by evanmwillhite** [comment]
@agarzola The way we install these Twig functions into Emulsify core is via [composer](https://github.com/fourkitchens/emulsify/blob/develop/composer.json#L35). So, if you want to use this now you could rerun `yarn` or `npm install` in the original project or just grab [the updated file](https://github.com/drupal-pattern-lab/attach-library-twig-extension/blob/master/pl_attach-library.function.php) and place it into `components/_twig-components/functions/`. Any new project will automatically get these updated versions.

**Comment by agarzola** [comment]
I could be missing something, but composer installed the tag for us, which is not the tip of `master`. I added the following patch in `composer.json` (using `composer-patches`) and it applied cleanly:
```json
"drupal-pattern-lab/attach-library-twig-extension": {
  "Fix multiple JS libraries": "https://github.com/drupal-pattern-lab/attach-library-twig-extension/compare/v1.0.0...f7ad065.diff"
}
```

**Comment by evanmwillhite** [comment]
Oh wow, I think you're right. So sorry I missed that. I've pushed up a new tag to encapsulate those changes. Thank you again!

**Comment by agarzola** [comment]
Thank you for the quick response, @evanmwillhite! :)

**Comment by evanmwillhite** [comment]
No problem, thank YOU!

**Pull request merged**
